-- Starting content for the Resolve UK Portal. Generated by scripts/build-seed.mjs from the content/ folder.
-- Run this once in the Supabase SQL editor, after schema.sql. It only adds what is missing,
-- so running it again never overwrites anything you have edited in the portal.

insert into public.documents (kind, slug, title, summary, body_md, pinned, period_start, period_end, status, published_at)
values ('blueprint', 'blueprint', 'Resolve UK Blueprint', 'The plan for the next stage: how a report gets from someone''s phone to a confirmed fix, what gets built and in what order, and the questions that need your help.', $md$## Summary

This is my plan for taking Resolve UK from the working prototype to something councils can actually use. It covers how a report travels from a photo on someone's phone to a confirmed fix, what I would build and in what order, and the questions I need your help with before going further.

It's based on the two emails you sent after the Week 1 report, and on your reply to the first version of this plan. Apart from the prototype, nothing described here has been built yet, so please read it as a draft. If something is wrong or missing, tell me and I'll change the plan before I build.

In short:

- A resident reports a problem. Staff at the responsible council or its contractor sign in to acknowledge it, schedule the work and mark it cleared. They only see reports for their own area, and they cannot verify their own work.
- The public is then shown that the problem has been cleared and asked whether they agree, with a photo. Once enough people agree, the report counts as verified. A Resolve reviewer can sign in to see everything and to verify, without being able to change what the council has done.
- The data will be hosted in the UK.
- I would start with a safe home for the data and a dashboard for whoever handles reports. The first three stages come to about 4.5 to 8.5 weeks of work. The routing and checking stage is the pilot, and it depends on a council agreeing to take part.

The time estimates are rough guesses. Licence terms and which council covers what also still need checking before I rely on them.

## How a report moves

Every report goes through the same set of stages. The middle ones are the stages you described: reported, responsible body identified, acknowledged, clearance scheduled, cleared and outcome verified. I've added three for when things don't go smoothly: duplicate, rejected and reopened. By "responsible body" I mean the council, or a contractor the council uses for that kind of work.

```mermaid
stateDiagram-v2
  state "Responsible body identified" as Routed
  state "Clearance scheduled" as Scheduled
  state "Outcome verified" as Verified
  [*] --> Reported: resident sends it in
  Reported --> Duplicate: matches an existing report
  Reported --> Rejected: not actionable
  Reported --> Routed
  Routed --> Acknowledged: responsible body sees it
  Acknowledged --> Scheduled: date set for the work
  Scheduled --> Cleared: responsible body says it's done
  Acknowledged --> Cleared: fixed without a scheduled date
  Cleared --> Verified: enough confirmed agreements
  Cleared --> Reopened: a confirmed photo shows it is still there
  Reopened --> Acknowledged: responsible body picks it up again
  Verified --> [*]
  Duplicate --> [*]
  Rejected --> [*]
```

*Figure 1. The stages a report can move through.*

One distinction matters more than the rest. When the responsible body marks a job as cleared, that's its own word. A report only becomes verified when independent people agree, with photos, that it's fixed. Keeping those two apart is what makes it possible to say how many fixes are genuinely confirmed.

Councils sign in to acknowledge, schedule and clear. They cannot verify. Each council only sees the reports for its own area, so London cannot see Manchester's. A Resolve view shows everything, and reviewers can verify from it, but cannot change what a council has done.

| Stage | What it means | Who sets it |
|---|---|---|
| Reported | Someone has sent it in. | The resident |
| Responsible body identified | The system knows who should deal with it: the council, or a contractor it uses. | Set automatically, or by staff |
| Acknowledged | The responsible body has seen it. | Council or contractor staff |
| Clearance scheduled | A date for the work is set. | Council or contractor staff |
| Cleared | The responsible body says the job is done. | Council or contractor staff |
| Outcome verified | Enough independent people agree, with photos, that it's fixed. | The platform, once a Resolve reviewer has confirmed the photos |
| Reopened | A confirmed photo shows the problem is still there. | A Resolve reviewer |
| Duplicate | It matches a report already made. | The resident when they send it, or staff |
| Rejected | Not something the responsible body can act on. | Council or contractor staff |

## Sending in a report

In the prototype, someone takes a photo, chooses a type and marks the spot. The next version adds a few steps behind the scenes.

```mermaid
flowchart TD
  subgraph Resident
    A["Open the app"] --> B["Take or choose a photo"]
    B --> C["Set the location: GPS or drop a pin"]
    C --> D["Pick the type, add a short description"]
  end
  subgraph App["The app"]
    D --> E{"Similar open report nearby?"}
    E -->|"Yes, same problem"| F["Add to the existing report"]
    E -->|"No or not sure"| G["Shrink the photo and upload it"]
  end
  subgraph DB["Saved"]
    G --> H["Save the report and its first history entry: Reported"]
    F --> I["Save the extra voice against that report"]
  end
  subgraph Auto["Behind the scenes"]
    H --> J["Work out the responsible body, a council or its contractor, from the location and type"]
    H --> K["AI suggests a category from the photo"]
    J --> L["History entry: responsible body identified"]
    K --> M{"Is the AI confident?"}
    M -->|"Yes"| N["Keep the suggestion"]
    M -->|"No"| O["Flag for a person to check"]
  end
  subgraph Staff["Council or contractor staff"]
    L --> P["Report appears on their dashboard"]
    N --> P
    O --> P
  end
```

*Figure 2. What happens when someone sends in a report.*

Before the report is saved, the app looks for an open report of the same type nearby and asks the person whether it's the same problem. If it is, their report is added to the existing one instead of creating a duplicate. I'd ask rather than merge automatically, because a wrong guess would hide a genuine second problem. I'd start with a distance of about 10 to 20 metres for potholes and 25 to 50 metres for other problems, then adjust once real reports come in.

The system then works out who is responsible from the location and the type of problem. That is usually a council, but councils often hand some of the work, such as waste clearance or road repairs, to a contractor, so the report can go to the contractor instead. Location alone isn't always enough. In areas with two levels of council, the county usually looks after potholes and the district looks after fly-tipping, which is why you noted that the level of council depends on the problem. I'll confirm who covers what, and who the contractors are, in the pilot area before relying on this.

The AI also suggests a category from the photo. If the AI isn't confident in its suggestion, the report is flagged for a person to look at.

## Checking a fix

When the responsible body marks a report as cleared, the app shows the public that it has been cleared and asks the people nearby, and anyone who backed the report, whether they agree it's fixed. Agreeing means sending a photo. The AI compares the photos and gives one of three answers: likely fixed, possibly not fixed, or needs a person to look. A Resolve reviewer then confirms whether the photo counts.

```mermaid
sequenceDiagram
  participant S as Council staff
  participant P as The platform
  participant R as Nearby residents
  participant A as AI photo check
  participant V as Resolve reviewer
  S->>P: Marks the report cleared
  P->>R: Shows it as cleared and asks: do you agree it's fixed?
  R->>P: Agrees, with a photo
  P->>A: Compares the photos
  A-->>P: Likely fixed, possibly not, or needs a person
  P->>V: Asks a reviewer to confirm the photo counts
  V->>P: Confirms it
  Note over P: After enough confirmed agreements the report becomes Verified
  R->>P: Disagrees
  alt With a photo
    P->>V: Sent to a reviewer to check
  else Without a photo
    P->>P: Noted, but it does not send the report back
  end
```

*Figure 3. How a fix gets checked.*

My draft rule, based on your reply, is this:

- A report becomes verified after 5 confirmed agreements, each with a photo. Five was your suggestion, and it's still a decision to confirm.
- Someone who disagrees without sending a photo doesn't count, and doesn't send the report back. Some people are just difficult, as you said.
- Someone who disagrees with a photo sends the report to a Resolve reviewer to check.
- If nobody responds, the report stays cleared but unverified, and is counted that way, so the verification figures stay honest.

Two points are still open, and are on the Decisions page: who checks each photo, and what happens in a remote area where 5 residents may never reply.

## Measuring results

Every change of stage is saved with the time it happened. That's what makes it possible to work out the figures in your benchmarking example. For instance:

- The number of days until the council marks a report cleared, for each council and each contractor. It stops at "cleared", not "verified", so that councils in remote areas aren't penalised when a problem was dealt with quickly but few people were around to confirm it.
- The share of reports cleared within five days.
- The share of cleared reports that were later verified.
- How often a problem returns to the same spot, meaning a new report close to one that was already fixed.

Hotspot maps and trends come later, once there's enough data for them to mean something.

## Order of work

I'd build in stages, each on top of the one before.

| Stage | What it adds | Hours | About how long |
|---|---|---|---|
| Foundation | A new database in the UK, a fuller set of issue types (fly-tipping, potholes, graffiti, abandoned vehicles, damaged infrastructure), smaller photos, councils and their contractors set up as responsible bodies, and the groundwork for recording each stage change and each intervention (what was done to fix a problem, and what it cost). | 10 to 20 | 1 to 2 weeks |
| Community | The "is this the same problem?" check, a count of people backing a report, and a public feed showing each report's progress. | 12 to 24 | 1.5 to 2.5 weeks |
| Staff dashboard | Sign-in for council staff, who see only their own area, plus a Resolve view of everything for reviewers. A list, map and filters, and buttons to acknowledge, schedule and clear. | 24 to 40 | 2.5 to 4 weeks |
| AI help | Suggested categories with a confidence level, checked by staff. Needs extra time to tune on real reports. | 10 to 20 | 1 to 2 weeks |
| Pilot: routing and checking fixes | Automatic routing to the right council or contractor for the pilot area, the public "do you agree it's fixed?" step with photos, and the verification rule. | 27 to 49 | 2.5 to 5 weeks |
| More AI checks | Naming the type of waste, estimating how much there is, and flagging items that look hazardous so they're escalated. Needs plenty of real reports to tune against, so I haven't sized it. | Later | Later |
| Following an area | Alerts about problems near a place, for example within a mile of a village, and a view of an area's open problems for community groups. Needs a way to send alerts, so it comes after the core stages. | Later | Later |
| Comparing performance | Public pages with comparable performance and outcome measures for councils and contractors. Needs months of real data first, so I haven't sized it. | Later | Later |

The first three stages come to roughly 46 to 84 hours, or 4.5 to 8.5 weeks. With AI help it's 56 to 104 hours, or 5.5 to 10.5 weeks. These are rough guesses and could be out by half again either way. They assume about 10 hours a week on Resolve UK, because my time is shared with another project. The pilot stage also depends on a council taking part, so no number of hours can promise it.

<div class="chart"><div class="wf" role="img" aria-label="Schedule in weeks at about 10 hours a week: Foundation weeks 1 to 2.5, Community weeks 2.5 to 4.5, Staff dashboard weeks 4.5 to 7.5, AI help weeks 7.5 to 9, the pilot weeks 9 to 13, which also depends on a council.">
<div class="wf-corner">Week</div>
<div class="wf-weeks"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span>8</span><span>9</span><span>10</span><span>11</span><span>12</span></div>
<div class="wf-label">Foundation</div>
<div class="wf-track"><div class="wf-bar" style="grid-column: 1 / 4">1.5 wk</div></div>
<div class="wf-label">Community</div>
<div class="wf-track"><div class="wf-bar" style="grid-column: 4 / 8">2 wk</div></div>
<div class="wf-label">Staff dashboard</div>
<div class="wf-track"><div class="wf-bar" style="grid-column: 8 / 14">3 wk</div></div>
<div class="wf-label">AI help</div>
<div class="wf-track"><div class="wf-bar" style="grid-column: 14 / 17">1.5 wk</div></div>
<div class="wf-label">Pilot: routing and checking fixes<small>needs a council</small></div>
<div class="wf-track"><div class="wf-bar uncertain" style="grid-column: 17 / 25">4 wk</div></div>
</div></div>

*Figure 4. The stages laid out over weeks, at about 10 hours a week. The dashed bar is the pilot, and it depends on a council agreeing to take part. If another project takes priority for a while, everything moves later.*

## Where this leads

Your second email described three phases. This plan builds the first one. The other two come later, because they depend on having real data.

| Phase | What it covers | When |
|---|---|---|
| 1. Report, route, track, resolve, verify | Everything in the stages above. | This plan |
| 2. Analyse, compare, spot recurring problems | Hotspots, comparable performance measures for councils and contractors, and places where the same problem keeps coming back. | After months of real reports |
| 3. Predict, intervene, measure | Predictive hotspot identification and preventative intervention, then checking whether the intervention worked. | Later, once there's enough good data |

Prediction isn't part of the first build. It needs enough good-quality data to build and check, so I'd put it on the roadmap rather than promise it at launch.

What makes all of this possible is the record. As you put it, the valuable part is the closed loop: the problem, the response, what was done about it, the outcome, and whether it came back. So from the first real report, the system saves each stage change with its time, and each intervention with what was done, who did it and what it cost, even though the analysis comes later.

Over time that data could be useful to government, waste operators, insurers, housing associations, researchers and the media. That's a question for later, but keeping the records consistent from the start is what keeps it open.

One item on your list, repeat offenders, needs care, because tying reports to individual people raises data protection questions. I'd start with repeat locations, which don't.

Once there are enough real reports to tune against, the AI checks can also name the type of waste, estimate how much there is, and flag items that look hazardous so they're escalated. Following an area, for example "tell me about problems within a mile of my village", is planned for later too. It needs a way to send alerts, so it comes after the core stages.

## Your questions, and my answers

These are the questions you asked after the Week 1 report, with my answers. Where you've since made a decision, it's noted here and recorded on the Decisions page.

### What does "shipped" mean?

Sorry, that section was too technical. It just means what's finished and working. You can open the prototype on a phone, report a problem with a photo and a location, and see it show up in a list. I rewrote it in plain language in the Week 1 report.

### What are the timing requirements for the next steps?

I can't give firm dates yet, but the first three stages should take about 4.5 to 8.5 weeks, or up to 10.5 with the AI part. That's at about 10 hours a week on Resolve UK, because my time is split with another project. If you'd rather one of the two came first, tell me and I'll adjust. Anything that needs a council can't be dated until one is on board. The full breakdown is under Order of work.

### Where is the data, and what would it take to move it?

At the moment the prototype's data is in Seoul, South Korea. I picked that region for convenience while building, and it only holds test reports. You've said UK hosting is best, so that's decided: the data moves to a UK location before any real reports come in. UK law doesn't ban storing data abroad, but it adds extra requirements, and councils will most likely ask for UK hosting anyway.

Moving now is easy because there's nothing real to move. It's about an hour or two of work and costs nothing extra. Doing it later, with real reports and photos in the database, is harder and riskier. So I'd do it first, in London, and set it up under an account that can be handed over to you or your organisation. I'm also changing how photos are stored so a later move can't break their links.

### What happens when the free usage runs out, and what does it cost?

The prototype runs on free plans for the database and photos (Supabase) and for the website (Vercel). Photo storage would run out first. The free plan has about 1 GB, and full-size phone photos are 3 to 5 MB each, so that's a few hundred reports. Shrinking photos when they're uploaded fixes most of that. If the limit were hit, uploads could stop working, so I'd upgrade before then.

The paid plans start at $25 a month for Supabase and $20 a month for Vercel, so about $45 a month for a pilot, plus the cost of the AI features once I know how many reports to expect. Vercel's free plan is for non-commercial use only, so a real pilot should be on the paid one anyway. I checked both companies' pricing pages on 20 September 2026 and these figures were current then. Supabase's price can rise if a project goes beyond its included allowance, and Vercel's covers one developer, with each extra developer costing another $20 a month.

### Can you match a report's location to others nearby, to stop duplicates?

Yes. Before a report is saved, the app can check for an open report of the same type nearby and ask the person whether it's the same problem. I'd ask rather than merge automatically, because a wrong guess could hide a real second problem. The distance is still to be decided. I'd start at about 10 to 20 metres for potholes and 25 to 50 for other problems, then adjust once real reports come in. It also gives you the shared view of an incident that you described. Sending in a report shows where it fits.

### Surely most people have GPS on?

You're right that most phones have it and most people will allow it, so most locations will be fine. I'd still keep the manual pin, for a few reasons. GPS is only accurate to about 5 to 20 metres, and worse between tall buildings. People often report later from home, when the phone's location is their house. And some people will be on a computer or will say no to location sharing. So the app uses GPS first, lets people correct it, and records how accurate it was. It's a small risk, not a big one.

### Which area would you suggest for the first pilot?

You suggested Huddersfield or Colchester, depending on whether a council agrees, which is outside your control.

Huddersfield is the simpler technical start: one council covers potholes, fly-tipping and the rest there, so reports have one place to go. Colchester is your preference if it's as easy, and it's your home town, which may open doors. As far as I know it has two levels of council, with the county looking after roads and the city council looking after fly-tipping and waste, so a report there can need routing to either. The plan already handles that, but it means a little more setup. I still need to check who covers what in both places.

## Technical appendix

This part is for whoever builds or takes over the system. Everyone else can skip straight to the questions at the end.

### How the pieces connect

```mermaid
flowchart TB
  subgraph Device["Resident's phone or browser"]
    PWA["Resolve UK app"]
  end
  subgraph Host["Vercel"]
    Static["App files only"]
  end
  subgraph Supa["Supabase, UK region"]
    Auth["Auth: staff and reviewer sign-in"]
    DB[("Postgres + PostGIS")]
    Store[("Storage: photos")]
    Fn["Edge Functions: routing + AI calls"]
  end
  subgraph Ext["External"]
    AI["AI service"]
    Tiles["Map tiles"]
  end
  Bounds["Open boundary data"] -.->|"loaded once for the pilot area"| DB
  Static -->|"serves"| PWA
  PWA -->|"reports, supports"| DB
  PWA -->|"shrunk photos"| Store
  PWA -->|"staff sign-in"| Auth
  PWA -->|"map images"| Tiles
  DB -->|"new report event"| Fn
  Fn -->|"photo + category question"| AI
  Fn -->|"responsible body + suggestion"| DB
```

*Figure 5. Where the data lives and which parts talk to each other.*

The AI key stays inside a server-side function and never reaches the browser. Vercel only serves the app's files and holds no data.

### Data model

The main change from the prototype is that a report's history becomes a list of entries that only ever grows. The current status is then a shortcut copied from the latest entry, not the source of truth.

```mermaid
erDiagram
  RESPONSIBLE_BODIES ||--o{ REPORTS : "is responsible for"
  RESPONSIBLE_BODIES ||--o{ STAFF_PROFILES : employs
  RESPONSIBLE_BODIES |o--o{ RESPONSIBLE_BODIES : "contractor works for"
  RESPONSIBLE_BODIES |o--o{ INTERVENTIONS : "carries out"
  CATEGORIES ||--o{ REPORTS : classifies
  REPORTS ||--|{ REPORT_EVENTS : "has history"
  REPORTS ||--o{ REPORT_SUPPORTS : "confirmed by"
  REPORTS ||--o{ INTERVENTIONS : "fixed by"
```

*Figure 6. How the tables relate to each other. The fields in each table are listed underneath.*

| Table | Fields |
|---|---|
| responsible_bodies | id, name, kind (council or contractor), tier (unitary, county or district; councils only), works_for_id (the council a contractor works for), functions (for example highways, waste, streetscene), boundary (councils only) |
| categories | code, label, function (which responsibility owns this type of issue) |
| reports | id, category_code, description, location, location_accuracy_m, location_source (gps or manual), photo_path, responsible_body_id (empty until routed), current_status (copied from the latest history entry), ai_category, ai_confidence, duplicate_of, created_at |
| report_events | id, report_id, status, actor_type (citizen, staff, reviewer, ai or system), actor_id, note, photo_path, data (extra details), created_at |
| report_supports | id, report_id, device_token, kind (same_issue, still_there or fixed), photo_path, ai_result, review_status (pending, confirmed or rejected), reviewed_by, created_at |
| interventions | id, report_id, body_id, type (cleared, camera, barrier, signage, enforcement or other), description, cost_pence (optional), done_at |
| staff_profiles | id (same as the sign-in id), body_id, role (staff, reviewer or resolve_admin), display_name |

Photos are stored by path, not full URL, so moving to a new project never breaks a link. Location accuracy is kept so the nearby check can allow for GPS error. Interventions record what was done about a problem, by whom, and what it cost.

Routing picks the council whose boundary contains the point and whose responsibilities include the issue type. If that council has a contractor for that kind of work, the report goes to the contractor. That handles areas where the county and district split the work. Following an area will need an extra `area_follows` table, which comes with that later stage.

### Who can see and change what

| Who | Reports | History | Photos |
|---|---|---|---|
| Public | Read. Create with type, description, location and photo only. Cannot set status or responsible body. Can agree or disagree that a fix worked, with a photo. | Read the status timeline. | Read (decision pending). |
| Council or contractor staff | Read reports for their own area only. | Add acknowledge, schedule and clear entries for their own area. Cannot add verification. | Upload evidence photos. |
| Resolve reviewer | Read everything. | Add verification entries. Cannot change or remove anything a council added. | Read everything. |
| Resolve admin | Everything, plus manage responsible bodies, issue types and accounts. | Everything. | Everything. |
| Nobody | Deletes reports. | Edits or deletes past entries (admin exceptions only). | Not applicable. |

These rules are enforced in the database itself (row-level security), not only in the app, so a bug in the app can't quietly expose data.

### What changes in the current prototype

- Issue types grow from three to five: fly-tipping, potholes, graffiti, abandoned vehicles and damaged infrastructure.
- The form records GPS accuracy, and photos are shrunk before upload and stored by path.
- Submitting also writes the first history entry, and the list shows the status timeline instead of a single word.
- New: sign-in for council staff and reviewers, and the dashboard. The Supabase keys move to the new UK project.

### Handover checklist

- Accounts (Supabase, Vercel, GitHub) sit in organisations that can be handed over by adding the new owner, not by sharing a password. Two-factor sign-in is on.
- The database structure lives in the repository as migration files, so the whole database can be recreated in any region or account.
- The README lists every environment variable, how to deploy, and how to rotate keys. Secrets live in each platform's secret store, never in chat or email.
- Backups are decided on purpose. The free tier may not include them, so confirm before real data arrives.
- There is a list of every third-party service used, with what it costs and who pays.
$md$, true, null, null, 'published', '2026-09-19T12:00:00Z')
on conflict (slug) do nothing;

insert into public.documents (kind, slug, title, summary, body_md, pinned, period_start, period_end, status, published_at)
values ('weekly', 'week-1', 'Week 1 Report', 'What was built in the first week, what comes next, and the questions that were asked.', $md$This week I built the first working version of Resolve UK. You can try it yourself on the Progress page. Open it on a phone, report a problem with a photo and a location, and it appears in a list with its status.

Everything so far comes from my own reading of the pitch deck, not from a process you've confirmed. The reporting loop (send in a problem, see what happened to it) works whichever way the rest turns out, so it was a safe place to start. Before I build further into routing and fixes, I'd like to understand how you expect those parts to work. My questions are at the end.

## What I built

Four things are in place.

- It works like an app on a phone. Open the website, choose "Add to Home Screen", and it sits alongside your other apps. There's nothing to download from an app store.
- Reports are stored safely online. Each report and its photo are saved on a secure hosted service, so nothing is lost when the phone is closed.
- There's a form for reporting a problem. You choose the type (fly-tipping, pothole or other), write a short description, add a photo, and mark where it is, either with the phone's location or by placing a pin on a map.
- There's a list of reports. Everything submitted shows up with its photo, type and status. For now every report says "Reported", because no council is connected yet to update it.

## What comes next

I see five stages, building outward from this first one towards the platform described in the pitch deck.

1. Reporting basics. This is what you can try today.
2. A feed instead of a list. Each report would be shown like a post on a social timeline, with the outcome beside it once there is one, so you see the problem and the fix together. I'd also add a light way for people to see their own reports without a full login, and let a report sent with no signal go through once the signal returns.
3. AI help with sorting. The app would suggest the type of problem from the photo, and how urgent it looks, instead of relying on the dropdown.
4. Sending reports to the right council, and checking fixes. Reports go to the responsible local authority, and AI helps confirm that a fix really happened before a report is marked resolved.
5. Public dashboards. Comparable performance measures for councils, and access for councils, housing associations and waste operators.

## Things to be aware of

These are the trade-offs I made to move quickly this week, roughly in order of importance. None of them stops me continuing, but they're worth deciding on deliberately before this becomes a pilot.

- Reports are public and there's no login. Anyone who opens the app sees every report, not just their own, and anyone with the link can submit one. That's fine for testing, but access needs to be controlled properly before wider use.
- The app needs an internet connection. Being installable doesn't mean it works offline. It can't send or show reports without a signal, which matters in places like rural fly-tipping spots. Fixing that means saving reports on the phone and sending them later, and I plan to do it in stage 2.
- I haven't decided where the data should live. The database was set up in whichever region was quickest, which isn't necessarily the UK or EU. Moving it later means rebuilding it, so this should be settled before any real citizen data is collected.
- The prototype is on a free hosting plan. It's fine for a prototype, but it pauses after a week of inactivity and has limits on storage and traffic. A pilot with real users will need a paid plan.
- Nobody checks the photos. Once reports are visible to others, and especially once the feed becomes the main view, inappropriate, duplicate or irrelevant photos become a real question. Storage cost grows with volume too.
- Placing a pin by hand is less exact than GPS. If someone declines to share their location they tap the map instead. That works for now, but it will matter once a report has to be matched to the right council's boundary.
- The status never moves on from "Reported". That's intentional at this stage, because no council is connected yet to update it. I'm mentioning it so it isn't mistaken for a fault.

## Questions I asked

You replied on 19 and 20 September, and your answers are reflected in the Blueprint and on the Decisions page. For the record, these are the five questions I asked.

1. How should a report reach the people who act on it: a dashboard checked by hand, or a link into a system a council already uses?
2. Who deals with these reports today, and is there an existing process or contact I should work with?
3. What counts as resolved, and who decides?
4. Is there a specific council or area I should design the first version around?
5. Are there existing commitments about how data is handled that I need to follow?
$md$, false, '2026-09-15', '2026-09-19', 'published', '2026-09-18T12:00:00Z')
on conflict (slug) do nothing;

insert into public.documents (kind, slug, title, summary, body_md, pinned, period_start, period_end, status, published_at)
values ('weekly', 'week-2', 'Week 2 Report', 'The plan, your feedback and the decisions it led to, the prototype''s new design, and what''s waiting on you.', $md$The plan for the next stage is written, and it has already been through a round of your feedback. The prototype has a cleaner design and proper branding. And the documents, questions and progress now have a private home that only you and I can open.

## What got done

- **The Blueprint.** Written, shared, then updated after your replies. The Updates list on the Progress page says exactly what changed.
- **Decisions recorded from your replies.** UK hosting; what councils can and can't do; the pilot stage; and measuring days until a council marks a report cleared.
- **The prototype.** A cleaner, more modern design with light and dark modes, the Resolve logo and app icons, and a map that works from anywhere. The live demo is on the Progress page.
- **A private portal.** One place for the Blueprint, the progress log, the weekly reports, the questions and the decisions, with a sign-in for you and one for me.

## Decisions made this week

- The data is hosted in the UK.
- Each council only sees reports for its own area, and a Resolve view sees everything.
- Councils can acknowledge, schedule and clear, but they can't verify.
- The routing and checking stage is the pilot.
- Councils are measured on days until they mark a report cleared, not days until it's verified.
- Councils and contractors are approached once there's a prototype that looks good and works.

## Waiting on you

These are on the Questions page:

- Whether 5 confirmed agreements, each with a photo, is the right rule for a fix to count as verified, and who checks each photo.
- What should happen when someone disagrees and sends a photo.
- What to do in a remote area where 5 residents may never reply.
- Whether to start the pilot in Colchester, which has two levels of council, or in Huddersfield, which has one.
- What the plan for testing Resolve UK is.

## Next

- Confirm the verification rule with you, so the pilot stage can be sized properly.
- Start the Foundation stage: the database in the UK, the wider set of issue types, and smaller photos.
- [Anything else planned for next week.]

## Time

[Hours spent this week, and how they compare with the estimate in the Blueprint.]
$md$, false, '2026-09-19', '2026-09-25', 'draft', null)
on conflict (slug) do nothing;

insert into public.questions (document_id, key, prompt, why, note, position, status)
select d.id, 'q1', 'Who will check the dashboard at the start, and who marks a report as cleared: your team or the council''s staff?', 'This tells me who needs a login.', 'Answered by email on 20 September: each council sees only its own area, a Resolve view sees everything, and councils can acknowledge, schedule and clear but not verify.', 1, 'closed'
from public.documents d where d.slug = 'blueprint'
on conflict (key) do nothing;

insert into public.questions (document_id, key, prompt, why, note, position, status)
select d.id, 'q2', 'How do you plan to approach a council, and do you have a contact or a way in?', 'Reports only get fixed if a council takes part.', 'Answered by email on 20 September: councils and contractors will be approached once there''s a prototype that looks good and works, and you can usually get a meeting.', 2, 'closed'
from public.documents d where d.slug = 'blueprint'
on conflict (key) do nothing;

insert into public.questions (document_id, key, prompt, why, note, position, status)
select d.id, 'q3', 'What is the plan for testing Resolve UK?', 'This helps me decide where to start.', null, 3, 'open'
from public.documents d where d.slug = 'blueprint'
on conflict (key) do nothing;

insert into public.questions (document_id, key, prompt, why, note, position, status)
select d.id, 'q4', 'Should a report count as verified after 5 people agree, each with a photo, and who should check each photo: the AI, a Resolve reviewer, or both?', 'This sets how much checking falls on your team, and what "verified" means in the figures.', null, 4, 'open'
from public.documents d where d.slug = 'blueprint'
on conflict (key) do nothing;

insert into public.questions (document_id, key, prompt, why, note, position, status)
select d.id, 'q5', 'If someone disagrees and sends a photo, should a Resolve reviewer check it and send the report back to the council if it''s right?', 'Some people disagree just to be difficult, so a single complaint shouldn''t reopen a fix.', null, 5, 'open'
from public.documents d where d.slug = 'blueprint'
on conflict (key) do nothing;

insert into public.questions (document_id, key, prompt, why, note, position, status)
select d.id, 'q6', 'In a remote area where 5 residents may never reply, should a Resolve reviewer be able to verify a fix from one clear photo?', 'Otherwise a fix in a quiet area could stay unverified forever.', null, 6, 'open'
from public.documents d where d.slug = 'blueprint'
on conflict (key) do nothing;

insert into public.questions (document_id, key, prompt, why, note, position, status)
select d.id, 'q7', 'Colchester has two levels of council, so a report there may need routing to two places. Are you happy to start there, or should Huddersfield go first?', 'Two levels means two routes to set up, which is a little more work. The plan already allows for it, and I still need to check who covers what.', null, 7, 'open'
from public.documents d where d.slug = 'blueprint'
on conflict (key) do nothing;

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'Where the data is hosted', 'The prototype''s test data is in Seoul for now.', 'decided', 'In the UK (London). The data moves before any real reports come in.', '2026-09-20', null, 1
where not exists (select 1 from public.decisions where title = 'Where the data is hosted');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'What each council can see', 'For example, London cannot see Manchester''s reports.', 'decided', 'Each council sees only the reports for its own area. A Resolve view sees everything.', '2026-09-20', null, 2
where not exists (select 1 from public.decisions where title = 'What each council can see');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'What councils can do, and what they can''t', null, 'decided', 'Councils can acknowledge, schedule and clear. They cannot verify. Resolve reviewers can verify and see the data, but cannot change what a council has done.', '2026-09-20', null, 3
where not exists (select 1 from public.decisions where title = 'What councils can do, and what they can''t');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'What the pilot is', null, 'decided', 'The routing and checking stage is the pilot stage.', '2026-09-20', null, 4
where not exists (select 1 from public.decisions where title = 'What the pilot is');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'What the time measure counts', null, 'decided', 'Days until the council marks a report cleared, not until it''s verified, so councils in remote areas aren''t penalised when a problem was dealt with quickly.', '2026-09-20', null, 5
where not exists (select 1 from public.decisions where title = 'What the time measure counts');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'When councils and contractors are approached', null, 'decided', 'Once there''s a prototype that looks good and works. Ms Kay arranges the meetings.', '2026-09-20', null, 6
where not exists (select 1 from public.decisions where title = 'When councils and contractors are approached');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'How many confirmations before a report counts as verified', 'Ms Kay suggested 5. To confirm: 5 agreements, each with a photo?', 'open', null, null, 'Before the pilot stage is built', 7
where not exists (select 1 from public.decisions where title = 'How many confirmations before a report counts as verified');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'Who checks each public photo', 'The AI, a Resolve reviewer, or both.', 'open', null, null, 'Before the pilot stage is built', 8
where not exists (select 1 from public.decisions where title = 'Who checks each public photo');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'What happens when someone disagrees with a photo', 'Proposed: a Resolve reviewer checks it and sends the report back to the council if it''s right. Disagreeing without a photo does nothing.', 'open', null, null, 'Before the pilot stage is built', 9
where not exists (select 1 from public.decisions where title = 'What happens when someone disagrees with a photo');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'Remote areas where 5 residents may never reply', 'Proposed: a Resolve reviewer can verify from one clear photo.', 'open', null, null, 'Before the pilot stage is built', 10
where not exists (select 1 from public.decisions where title = 'Remote areas where 5 residents may never reply');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'Where the pilot starts', 'Huddersfield (one council) or Colchester (two levels of council, and Ms Kay''s home town). It depends on a council agreeing, which is outside Ms Kay''s control.', 'open', null, null, 'Before the pilot stage is built', 11
where not exists (select 1 from public.decisions where title = 'Where the pilot starts');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'Whether photos appear publicly straight away, or are checked first', 'Photos can show faces and number plates.', 'open', null, null, 'Before the community stage', 12
where not exists (select 1 from public.decisions where title = 'Whether photos appear publicly straight away, or are checked first');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'Whether people who report need an account, or can stay anonymous', null, 'open', null, null, 'Before the community stage', 13
where not exists (select 1 from public.decisions where title = 'Whether people who report need an account, or can stay anonymous');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'How long reports and photos are kept', 'Needs UK data protection advice.', 'open', null, null, 'Before real reports come in', 14
where not exists (select 1 from public.decisions where title = 'How long reports and photos are kept');

insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)
select 'Which project comes first when time is short', 'It sets the real timeline for Resolve UK.', 'open', null, null, 'When timings are agreed', 15
where not exists (select 1 from public.decisions where title = 'Which project comes first when time is short');

insert into public.updates (title, summary, details_md, released_on, version, demo_url, status)
select 'First working prototype', 'Report a problem with a photo, a category and a location, and see it in a list. It installs on a phone like an app.', $md$You can now:

- Open the prototype on a phone and add it to the home screen.
- Report a problem: pick a type, describe it, add a photo, and mark the location using the phone or a map pin.
- See every report in a list with its photo and status.

Every report shows "Reported" for now, because no council is connected yet.$md$, '2026-09-18', 'v0.1', null, 'published'
where not exists (select 1 from public.updates where title = 'First working prototype');

insert into public.updates (title, summary, details_md, released_on, version, demo_url, status)
select 'Cleaner design and branding', 'A more modern look with light and dark modes, the Resolve logo and app icons, and a map that works from anywhere.', $md$What changed:

- A cleaner layout with a simpler form, clearer buttons and a dropdown that looks the same on every device.
- Light and dark modes that follow the phone's setting.
- The Resolve logo in the header, and proper app icons for the home screen.
- The map opens on a world view, so it works wherever someone is.$md$, '2026-09-19', 'v0.2', null, 'published'
where not exists (select 1 from public.updates where title = 'Cleaner design and branding');

insert into public.updates (title, summary, details_md, released_on, version, demo_url, status)
select 'Blueprint, first version', 'The plan for the next stage, with the questions that needed your help.', $md$Covers how a report moves from a phone to a confirmed fix, what gets built and in what order, rough timings, and your questions answered.$md$, '2026-09-19', null, null, 'published'
where not exists (select 1 from public.updates where title = 'Blueprint, first version');

insert into public.updates (title, summary, details_md, released_on, version, demo_url, status)
select 'Blueprint updated with your answers', 'Your decisions from 20 September are now in the plan.', $md$What changed:

- **Hosting.** UK hosting is decided.
- **Who can do what.** Councils see only their own area and can acknowledge, schedule and clear, but not verify. A Resolve view sees everything and can verify without changing what a council did.
- **How a fix is checked.** The public is shown that a report is cleared and asked whether they agree, with a photo. Disagreeing without a photo doesn't send it back. Five confirmations is the draft rule.
- **The pilot.** Routing and checking fixes is now called out as the pilot stage.
- **Measuring councils.** The measure stops at "cleared", not "verified".
- **The AI step.** The diagram now says it is the AI being confident in its suggestion.
- **Decisions.** The decisions that can wait now have their own page, so they aren't forgotten.$md$, '2026-09-20', null, null, 'published'
where not exists (select 1 from public.updates where title = 'Blueprint updated with your answers');

insert into public.updates (title, summary, details_md, released_on, version, demo_url, status)
select 'Private portal', 'One private place for the Blueprint, progress, weekly reports, questions and decisions, with a sign-in for you and one for me.', $md$Your answers are saved to your account, so you can see them from any of your devices and go back to check earlier ones. Replies from me appear underneath.$md$, '2026-09-20', null, null, 'draft'
where not exists (select 1 from public.updates where title = 'Private portal');

insert into public.settings (key, value) values ('prototype_url', 'https://resolve-uk-ten.vercel.app/') on conflict (key) do nothing;
insert into public.settings (key, value) values ('prototype_version', 'v0.2') on conflict (key) do nothing;
insert into public.settings (key, value) values ('prototype_note', 'Cleaner design, light and dark modes, the Resolve logo and app icons.') on conflict (key) do nothing;
insert into public.settings (key, value) values ('prototype_updated', '2026-09-19') on conflict (key) do nothing;
