// Turns content/seed.json and the Markdown files in content/ into supabase/seed.sql.
// Run with:  npm run seed
// The generated file only ADDS what is missing, so running it again never overwrites edits made in the portal.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const seed = JSON.parse(readFileSync(join(root, 'content', 'seed.json'), 'utf8'))

const str = (s) => (s == null ? 'null' : "'" + String(s).replace(/'/g, "''") + "'")
const bool = (b) => (b ? 'true' : 'false')
const num = (n) => (n == null ? 'null' : String(Number(n)))

// Long Markdown goes in dollar quotes so nothing inside it needs escaping.
function md(text) {
  let n = 0
  let tag = 'md'
  while (text.includes('$' + tag + '$')) tag = 'md' + ++n
  return `$${tag}$${text}$${tag}$`
}

const out = []
out.push('-- Starting content for the Resolve UK Portal. Generated by scripts/build-seed.mjs from the content/ folder.')
out.push('-- Run this once in the Supabase SQL editor, after schema.sql. It only adds what is missing,')
out.push('-- so running it again never overwrites anything you have edited in the portal.')
out.push('')

for (const d of seed.documents) {
  const body = readFileSync(join(root, 'content', d.file), 'utf8').trim() + '\n'
  out.push(
    `insert into public.documents (kind, slug, title, summary, body_md, pinned, period_start, period_end, status, published_at)\n` +
      `values (${str(d.kind)}, ${str(d.slug)}, ${str(d.title)}, ${str(d.summary)}, ${md(body)}, ${bool(d.pinned)}, ` +
      `${str(d.period_start)}, ${str(d.period_end)}, ${str(d.status)}, ${str(d.published_at)})\n` +
      `on conflict (slug) do nothing;\n`,
  )
}

for (const q of seed.questions) {
  out.push(
    `insert into public.questions (document_id, key, prompt, why, note, position, status)\n` +
      `select d.id, ${str(q.key)}, ${str(q.prompt)}, ${str(q.why)}, ${str(q.note)}, ${num(q.position)}, ${str(q.status)}\n` +
      `from public.documents d where d.slug = ${str(q.document)}\n` +
      `on conflict (key) do nothing;\n`,
  )
}

for (const d of seed.decisions) {
  out.push(
    `insert into public.decisions (title, detail, status, outcome, decided_on, needed_by, position)\n` +
      `select ${str(d.title)}, ${str(d.detail)}, ${str(d.status)}, ${str(d.outcome)}, ${str(d.decided_on)}, ${str(d.needed_by)}, ${num(d.position)}\n` +
      `where not exists (select 1 from public.decisions where title = ${str(d.title)});\n`,
  )
}

for (const u of seed.updates) {
  out.push(
    `insert into public.updates (title, summary, details_md, released_on, version, demo_url, status)\n` +
      `select ${str(u.title)}, ${str(u.summary)}, ${md(u.details_md || '')}, ${str(u.released_on)}, ${str(u.version)}, ${str(u.demo_url)}, ${str(u.status)}\n` +
      `where not exists (select 1 from public.updates where title = ${str(u.title)});\n`,
  )
}

for (const [key, value] of Object.entries(seed.settings)) {
  out.push(`insert into public.settings (key, value) values (${str(key)}, ${str(value)}) on conflict (key) do nothing;`)
}
out.push('')

writeFileSync(join(root, 'supabase', 'seed.sql'), out.join('\n'))
console.log('Wrote supabase/seed.sql')
